package com.itsthwng.twallpaper.ui.component.zipper.lib.transition

enum class TransitionType {
    PingPong,
    LinearTween,
    EaseInQuad,
    EaseOutQuad,
    EaseInOutQuad,
    EaseInCubic,
    EaseOutCubic,
    EaseInOutCubic,
    EaseInQuart,
    EaseOutQuart,
    EaseInOutQuart,
    EaseInQuint,
    EaseOutQuint,
    EaseInOutQuint,
    EaseInSine,
    EaseOutSine,
    EaseInOutSine,
    EaseInExpo,
    EaseOutExpo,
    EaseInOutExpo,
    EaseInCirc,
    EaseOutCirc,
    EaseInOutCirc,
    EaseInBounce,
    EaseOutBounce,
    EaseInOutBounce,
    Special1,
    Special2,
    Special3,
    Special4
}
